# Generated by Django 4.0.3 on 2022-08-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('project_details', models.TextField()),
                ('project_image', models.ImageField(blank=True, upload_to='project_image')),
                ('project_url', models.URLField(blank=True)),
                ('project_github_link', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
